port: 47209
theme: light
text_size: big
show_dates: false
show_gantt: true
show_calendar: true
show_weekends: false
auto_refresh: true
default_duration: 1
colors:
  default: '#8c8c8c'
  FIX: '#ff0000'
  FEAT: '#0080ff'
  REFACTOR: '#ffbf00'
  PERF: '#ff33ff'
  TESTS: '#269900'
  DOCS: '#663300'
  ENV: '#999900'
  MISC: '#339999'
